kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  # so eppudu ee pod expense namespace lo create avthundhi.. to see the pod
  # kubectl get pods -n expense
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: rithinthota/mysql:v1.0
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port